####################
##Tolerances
tolerance:precursor:10ppm
tolerance:fragment:20ppm

####################
## include linear matches
EVALUATELINEARS:true

#################
## Cross Linker + associated modifications
crosslinker:LinearCrosslinker:NAME:linear

##========================
##--Fixed Modifications
modification:fixed::SYMBOLEXT:cm;MODIFIED:C;DELTAMASS:57.021464

##========================
##--Variable Modifications
modification:variable::SYMBOLEXT:ox;MODIFIED:M;DELTAMASS:15.99491463

###################
## Digest
##Tryptic digest
digestion:PostAAConstrainedDigestion:DIGESTED:K,R;ConstrainingAminoAcids:P;NAME=Trypsin
##LysC digest
digestion:PostAAConstrainedDigestion:DIGESTED:K;ConstrainingAminoAcids:P;NAME=Lys-C

#####################################################################################################
##Fragment match settings

####################
## Non-Lossy Fragments to consider
fragment:BIon
fragment:YIon
## peptide ion should always be enabled, as otherwise no standard cross-linked fragments will be matched - also needed for precoursor-fragment matches
fragment:PeptideIon

###################
## Losses
loss:AminoAcidRestrictedLoss:NAME:H20;aminoacids:S,T,D,E;MASS:18.01056027;cterm
loss:AminoAcidRestrictedLoss:NAME:NH3;aminoacids:R,K,N,Q;MASS:17.02654493;nterm
loss:AIonLoss



#####################
## Generally lossy fragmenst will have a smaller impact on subscores then non-lossy versions of a fragment.
## But some subscores (anything called conservative) considere a fragment observed even if n neutral losses for that fragment where observed but not the fragment itself
## this defines how many loses are needed to make a fragment count as observed
## was actually hardcoded to 3 before
ConservativeLosses:3

####################
## isotop annotation
IsotopPattern:Averagin

####################
# if this is set to true also fragment matches are reported that are of by 1 dalton
# default: true
MATCH_MISSING_MONOISOTOPIC:true

########################################
## consider also matches to a precursor mass that
## are up to n Dalton (actually n*1.00335 Da) lighter
## this would account for missing isotope peaks in the MS1
missing_isotope_peaks:2

####################
## how many peaks to consider for mgc-search
mgcpeaks:10

###################
### Candidate selection
topmgchits:150
## how many combinations of alpha and beta peptides will be considered for final scoreing
topmgxhits:10

##################
## how many misscleavages are considered
missedcleavages:3

####################
## define a minimum peptide length (default 2)
MINIMUM_PEPTIDE_LENGTH:6

#####################
## IO-settings
BufferInput:100
BufferOutput:100

#####################
## Only write out the top match per spectrum
## defaults: false
TOPMATCHESONLY:false

#####################
## maximum mass of a peptide to be considered for fragmentation
## Default: 1.7976931348623157e+308
## the value will be lowered to the maximum found precoursor mass in the peak-list
MAXPEPTIDEMASS:4000

#####################
## some limits for generating modified peptides
## default: 3 and 20
MAX_MODIFICATION_PER_PEPTIDE:3
MAX_MODIFIED_PEPTIDES_PER_PEPTIDE:20

################
## Fragment Tree
FRAGMENTTREE:FU
